import { z } from "zod";
import { FINANCING_PURPOSES, LEAD_SOURCES } from "@/features/pre-assessment/constants";

export const preAssessmentSchema = z.object({
  financingAmount: z.number().min(1000, "Enter a financing amount of at least CAD $1,000"),
  financingPurpose: z.enum(FINANCING_PURPOSES.map((item) => item.value) as [string, ...string[]]),
  useOfFunds: z.string().min(20, "Describe the use of funds"),
  businessLegalName: z.string().min(2, "Enter the business legal name"),
  operatingName: z.string().optional(),
  businessNumber: z.string().optional(),
  industry: z.string().min(2, "Enter the industry"),
  province: z.string().min(2, "Enter the province"),
  yearsOperating: z.string().min(1, "Select operating history"),
  annualRevenue: z.string().min(1, "Select annual revenue range"),
  existingDebt: z.string().min(1, "Select existing debt level"),
  cashFlowProfile: z.string().min(1, "Select cash-flow profile"),
  collateralAvailable: z.string().min(1, "Select an option"),
  ownerEquityAvailable: z.string().min(1, "Select an option"),
  consumerPurpose: z.string().min(1, "Select an option"),
  realPropertySecurity: z.string().min(1, "Select an option"),
  securitiesBased: z.string().min(1, "Select an option"),
  decisionMakerName: z.string().min(2, "Enter full name"),
  decisionMakerRole: z.string().min(2, "Enter role / title"),
  authorizedDecisionMaker: z.string().min(1, "Select an option"),
  businessEmail: z.string().email("Enter a valid business email"),
  businessPhone: z.string().min(7, "Enter a business phone number"),
  mobilePhone: z.string().optional(),
  preferredContactMethod: z.string().min(1),
  preferredContactTime: z.string().min(1),
  leadSource: z.enum(LEAD_SOURCES.map((item) => item.value) as [string, ...string[]]),
  termsAccepted: z.boolean().refine((value) => value === true, {
    message: "You must accept the Pre-Assessment terms",
  }),
  accuracyConfirmed: z.boolean().refine((value) => value === true, {
    message: "You must confirm the information is accurate",
  }),
});

export type PreAssessmentFormValues = z.infer<typeof preAssessmentSchema>;

export const defaultPreAssessmentValues: PreAssessmentFormValues = {
  financingAmount: 250000,
  financingPurpose: "working-capital",
  useOfFunds: "",
  businessLegalName: "",
  operatingName: "",
  businessNumber: "",
  industry: "",
  province: "Ontario",
  yearsOperating: "",
  annualRevenue: "",
  existingDebt: "",
  cashFlowProfile: "",
  collateralAvailable: "",
  ownerEquityAvailable: "",
  consumerPurpose: "",
  realPropertySecurity: "",
  securitiesBased: "",
  decisionMakerName: "",
  decisionMakerRole: "",
  authorizedDecisionMaker: "",
  businessEmail: "",
  businessPhone: "",
  mobilePhone: "",
  preferredContactMethod: "email",
  preferredContactTime: "flexible",
  leadSource: "google-search",
  termsAccepted: false,
  accuracyConfirmed: false,
};

export const stepFields: (keyof PreAssessmentFormValues)[][] = [
  ["financingAmount", "financingPurpose", "useOfFunds"],
  ["businessLegalName", "operatingName", "businessNumber", "industry", "province", "yearsOperating"],
  ["annualRevenue", "existingDebt", "cashFlowProfile"],
  ["collateralAvailable", "ownerEquityAvailable"],
  ["consumerPurpose", "realPropertySecurity", "securitiesBased"],
  [
    "decisionMakerName",
    "decisionMakerRole",
    "authorizedDecisionMaker",
    "businessEmail",
    "businessPhone",
    "mobilePhone",
    "preferredContactMethod",
    "preferredContactTime",
  ],
  ["leadSource", "termsAccepted", "accuracyConfirmed"],
  [],
];
